// PROVIDED (from Lesson 1). You do not edit this file in Exercise 2.
#include "mm/codec.hpp"
namespace mm {
void put_u16_le(std::uint8_t* d, std::uint16_t v){ for(int i=0;i<2;++i) d[i]=std::uint8_t(v>>(8*i)); }
void put_u16_be(std::uint8_t* d, std::uint16_t v){ for(int i=0;i<2;++i) d[i]=std::uint8_t(v>>(8*(1-i))); }
void put_u32_le(std::uint8_t* d, std::uint32_t v){ for(int i=0;i<4;++i) d[i]=std::uint8_t(v>>(8*i)); }
void put_u32_be(std::uint8_t* d, std::uint32_t v){ for(int i=0;i<4;++i) d[i]=std::uint8_t(v>>(8*(3-i))); }
void put_u64_le(std::uint8_t* d, std::uint64_t v){ for(int i=0;i<8;++i) d[i]=std::uint8_t(v>>(8*i)); }
void put_u64_be(std::uint8_t* d, std::uint64_t v){ for(int i=0;i<8;++i) d[i]=std::uint8_t(v>>(8*(7-i))); }
std::uint16_t get_u16_le(const std::uint8_t* s){ std::uint16_t r=0; for(int i=0;i<2;++i) r=std::uint16_t(r|std::uint16_t(std::uint16_t(s[i])<<(8*i))); return r; }
std::uint16_t get_u16_be(const std::uint8_t* s){ std::uint16_t r=0; for(int i=0;i<2;++i) r=std::uint16_t(r|std::uint16_t(std::uint16_t(s[i])<<(8*(1-i)))); return r; }
std::uint32_t get_u32_le(const std::uint8_t* s){ std::uint32_t r=0; for(int i=0;i<4;++i) r|=std::uint32_t(s[i])<<(8*i); return r; }
std::uint32_t get_u32_be(const std::uint8_t* s){ std::uint32_t r=0; for(int i=0;i<4;++i) r|=std::uint32_t(s[i])<<(8*(3-i)); return r; }
std::uint64_t get_u64_le(const std::uint8_t* s){ std::uint64_t r=0; for(int i=0;i<8;++i) r|=std::uint64_t(s[i])<<(8*i); return r; }
std::uint64_t get_u64_be(const std::uint8_t* s){ std::uint64_t r=0; for(int i=0;i<8;++i) r|=std::uint64_t(s[i])<<(8*(7-i)); return r; }
}
